<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "event".
 *
 * @property int $id
 * @property string $date
 * @property string $name
 */
class Event extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'event';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date', 'name'], 'required'],
            [['date'], 'date', 'format' => 'php:d.m.Y'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Дата',
            'name' => 'Описание',
        ];
    }

    public function beforeSave($insert)
    {
        $this->date = Yii::$app->formatter->asDate($this->date, 'php:Y-m-d');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind();

        $this->date = Yii::$app->formatter->asDate($this->date, 'php:d.m.Y');
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        $config = [
            'name' => (new \DateTime($this->date))->format('Ymd') . ' ' . $this->name,
            'start_date' => $this->date,
            'is_dir' => true,
            'event_id' => $this->id,
        ];
        $config['short_name'] = $config['name'];
        if (($first_level_model = new Template($config))->save()) {
            $branches = ['jewelers' => 'Ювелиры'];
            $org_forms = ['ooo' => 'ООО', 'ip' => 'ИП'];
            $emp_counts = [1 => '1 сотр.', 2 => '>1 сотр.'];
            $items = [];
            foreach ($branches as $key => $branch) {
                $config['parent_id'] = $first_level_model->id;
                $config['branch'] = $key;
                foreach ($org_forms as $oKey => $org_form) {
                    $config['org_form'] = $oKey;
                    foreach ($emp_counts as $eKey => $emp_count) {
                        $config['name'] = "$branch $org_form $emp_count";
                        $config['short_name'] = $config['name'];
                        $config['emp_count'] = $eKey;
                        $items[] = $config;
                    }
                }
            }
            foreach ($items as $item) {
                if (($second_level_model = new Template($item))->save()) {
                    $types = [false => 'Действующие клиенты', true => 'Новые клиенты'];
                    $item['parent_id'] = $second_level_model->id;
                    foreach ($types as $tKey => $type) {
                        $item['is_new'] = $tKey;
                        $item['name'] = $type;
                        (new Template($item))->save();
                    }
                }
            }
        }
    }
}
